### ISSUE TITLE
버그 투성이

### ISSUE THREAD

**Issue by Hoto-Cocoa** [teamatus/twitterbot#2]
```C:\Users\Cocoa\twitterbot>node index.js
C:\Users\Cocoa\twitterbot\node_modules\twitterbot\index.js:32
}g
 ^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Cocoa\twitterbot\index.js:1:80)
    at Module._compile (module.js:570:32)
```
이렇게 나와서 해당 부분은 직접 수정을 했습니다. npm과 여기는 소스가 좀 다른가보죠?

```C:\Users\Cocoa\twitterbot>node index.js
C:\Users\Cocoa\twitterbot\node_modules\twitterbot\index.js:61
TwitterBot.prototype.media.createTweet = (data, text, timeout, callback) => {
                                       ^

TypeError: Cannot set property 'createTweet' of undefined
    at Object.<anonymous> (C:\Users\Cocoa\twitterbot\node_modules\twitterbot\index.js:61:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Cocoa\twitterbot\index.js:1:80)
    at Module._compile (module.js:570:32)
```
Why `twitterbot` 이전에 돌아가지 않으면 무의미 아닙니까..

**Comment by BasixKOR** [comment]
오타가 난 상태에서 커밋된 모양이군요.. 수정하겟습니다.

**Comment by Hoto-Cocoa** [comment]
1년이 지났는데도 그대로네요.
